version: "3.9"

services:
    api:
        build:
            context: .
            dockerfile: ./docker/local/django/Dockerfile
        command: /start
        volumes:
            - .:/app:z
            - static_volume:/app/staticfiles
            - media_volume:/app/mediafiles
        expose:
            - "8000"
        env_file:
            - .env
        depends_on:
            - postgres
        networks:
            - authors-api
    
    postgres:
        build:
            context: .
            dockerfile: ./docker/local/postgres/Dockerfile
        volumes:
            - local_postgres_data:/var/lib/postgresql/data
        env_file:
            - .env
        networks:
            - authors-api

    redis:
        image: redis:7-alpine
        networks:
            - authors-api

    celery_worker:
        build:
            context: .
            dockerfile: ./docker/local/django/Dockerfile
        command: /start-celeryworker
        volumes:
            - .:/app
        env_file:
            - .env
        depends_on:
            - redis
            - postgres
            
        networks:
            - authors-api

    flower:
        build:
            context: .
            dockerfile: ./docker/local/django/Dockerfile
        command: /start-flower
        volumes:
            - flower_data:/data
        env_file:
            - .env
        ports:
            - "5555:5555"
        depends_on:
            - redis
            - postgres
        networks:

    nginx:
        restart: always
        depends_on:
            - api
        volumes:
            - static_volume:/app/staticfiles
            - media_volume:/app/mediafiles
        build:
            context: ./docker/local/nginx
            dockerfile: Dockerfile
        ports:
            - "8080:80"
        networks:
            - authors-api


    networks:
    authors-api:
        driver: bridge

    volumes:
        static_volume:
        media_volume:
        local_postgres_data: {}
        local_postgres_data_backups: {}
